"""
GitHub Tools
Creates PRs with AI-generated fixes for CI/CD and Dockerfile issues.
"""
import base64
import os
from datetime import datetime

import httpx
import structlog

log = structlog.get_logger()


class GitHubTools:
    def __init__(self):
        self.token = os.getenv("GITHUB_TOKEN", "")
        self.headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        self.base = "https://api.github.com"

    async def create_fix_pr(
        self,
        repo: str,
        file_path: str,
        new_content: str,
        pr_title: str,
        pr_body: str,
    ) -> dict:
        """Create a branch + commit + PR with the AI fix."""
        branch_name = f"devops-ai-fix/{datetime.utcnow().strftime('%Y%m%d-%H%M%S')}"

        async with httpx.AsyncClient(headers=self.headers, timeout=30) as client:
            # 1. Get default branch SHA
            repo_resp = await client.get(f"{self.base}/repos/{repo}")
            if repo_resp.status_code != 200:
                return {"error": f"Repo not found: {repo}"}

            default_branch = repo_resp.json()["default_branch"]
            branch_resp = await client.get(
                f"{self.base}/repos/{repo}/git/ref/heads/{default_branch}"
            )
            sha = branch_resp.json()["object"]["sha"]

            # 2. Create new branch
            branch_resp = await client.post(
                f"{self.base}/repos/{repo}/git/refs",
                json={"ref": f"refs/heads/{branch_name}", "sha": sha},
            )
            if branch_resp.status_code not in (200, 201):
                return {"error": f"Failed to create branch: {branch_resp.text}"}

            # 3. Get current file SHA (if exists)
            file_resp = await client.get(
                f"{self.base}/repos/{repo}/contents/{file_path}",
                params={"ref": default_branch},
            )
            file_sha = file_resp.json().get("sha") if file_resp.status_code == 200 else None

            # 4. Create/update file
            encoded_content = base64.b64encode(new_content.encode()).decode()
            update_payload = {
                "message": f"fix: AI agent automated fix — {pr_title}",
                "content": encoded_content,
                "branch": branch_name,
            }
            if file_sha:
                update_payload["sha"] = file_sha

            update_resp = await client.put(
                f"{self.base}/repos/{repo}/contents/{file_path}",
                json=update_payload,
            )
            if update_resp.status_code not in (200, 201):
                return {"error": f"Failed to update file: {update_resp.text}"}

            # 5. Create PR
            pr_body_full = (
                f"{pr_body}\n\n"
                f"---\n"
                f"🤖 *This PR was automatically generated by the DevOps AI Agent.*\n"
                f"Please review before merging."
            )
            pr_resp = await client.post(
                f"{self.base}/repos/{repo}/pulls",
                json={
                    "title": f"[AI Fix] {pr_title}",
                    "body": pr_body_full,
                    "head": branch_name,
                    "base": default_branch,
                    "draft": True,  # Draft so humans review before merging
                },
            )

            if pr_resp.status_code in (200, 201):
                pr = pr_resp.json()
                return {
                    "success": True,
                    "pr_url": pr["html_url"],
                    "pr_number": pr["number"],
                    "branch": branch_name,
                }
            else:
                return {"error": f"Failed to create PR: {pr_resp.text}"}

    async def rerun_workflow(self, repo: str, run_id: int, failed_jobs_only: bool = True) -> dict:
        """Re-run a GitHub Actions workflow (failed jobs, or the whole run)."""
        if not self.token:
            return {"error": "GITHUB_TOKEN not configured"}
        suffix = "rerun-failed-jobs" if failed_jobs_only else "rerun"
        url = f"{self.base}/repos/{repo}/actions/runs/{int(run_id)}/{suffix}"
        async with httpx.AsyncClient(headers=self.headers, timeout=30) as client:
            try:
                resp = await client.post(url)
            except Exception as e:
                return {"error": str(e)}
        if resp.status_code in (201, 204):
            return {
                "success": True,
                "repo": repo,
                "run_id": int(run_id),
                "failed_jobs_only": failed_jobs_only,
                "message": (
                    f"GitHub Actions run {run_id} failed jobs re-queued"
                    if failed_jobs_only
                    else f"GitHub Actions run {run_id} re-queued"
                ),
            }
        return {
            "error": f"Failed to re-run GitHub Actions run {run_id}: {resp.status_code} {resp.text}"
        }
